### ISSUE TITLE
saving in database

### ISSUE THREAD

**Issue by yoooov** [thdoteo/php-random-avatars#1]
Bonjour théo, bravo et merci pour le dév de ton générateur :)
J'essai de l'incorporer à mon site qui posséde sa propre base de donnée, j'ai donc CREATE la table avatars dans mon actuelle bdd.
dans mon index j'ai bien ::
require_once (INCL_DIR . 'generator_avatars/randomAvatarsGenerator.php');
(...)
dbconn(true);
(...)
$avatar = new randomAvatarsGenerator($db);
$avatar->generate();
$avatar->checkPresetIsUnique();
$avatar->draw();
$avatar->saveInDB();
mais aucun avatar n'est stocké dans la bdd.... :(

Peux tu me détailler un peu le setup pour l'utilisation avec ma bdd ... ??
Par avance un grand merci !!!

IO

**Comment by theolepage** [comment]
Salut ! Merci ça me fait extrêmement plaisir :-).

As tu bien déclaré $db ? Par exemple comme ceci :
`$db = new PDO('mysql:host=HOST;dbname=DBNAME', 'USER', 'PASSWORD');`

Bonne soirée.

**Comment by theolepage** [comment]
Ah c'est bon je pense avoir trouvé ! La requête dans la base de donnée ne se faisait pas si l'image n'était pas enregistrée avant. C'est maintenant réglé ! Dit moi si ça fonctionne chez toi.

P.S. : Je vais réécrire le Readme avec de meilleures explications.

**Comment by yoooov** [comment]
Merci de ta réponse si rapide ;)
Je ne peux plus bosser sur le serveur tt de suite mais je fais les essais demain mat je te tiens au courant =]
Très bonne soirée!

**Comment by yoooov** [comment]
"La requête dans la base de donnée ne se faisait pas si l'image n'était pas enregistrée avant"
Super :) c'était bien ça l'image s'enregistre maintenant bien dans la table...
Il faut maintenant que j'adapte ta classe pour avoir une indexation des fichiers lors de l'enregistrement physique dans le dossier generated et ne plus avoir un écrasement systématique, il faut aussi que je modifie le code pour permettre soit une validation de l'avatar ou une regénération , cela pour chaque users de mon site...
Il se pourrait donc que j'ai à nouveau besoin de tes conseils ;)
Encore merci et bonne journée!!

**Comment by theolepage** [comment]
Yes ! Pas de soucis.
Le plus simple serait de nommer chaque avatar par l'id (unique) de l'utilisateur. Attention de ne pas oublier de mettre à jour la BDD si un utilisateur supprime son avatar/son compte ou qu'il change d'avatar (pour que l'ancien preset soit de nouveau utilisable par quelqu'un d'autre). Et pour l'adapter à ton site je pense que tu as vu qu'il était très simple de personnaliser les formes/couleurs au début de la class.
Si tu as envie d'améliorer la class n'hésites pas à faire un pull request.
Pour tes prochaines questions je te propose de m'envoyer un mail : theo@theolab.xyz :-).
A bientôt.
